### PR TITLE
Avoid adding incompatible arguments when creating application image

### LINKED ISSUE #296: Creating application image fails with certain DSL options
As of `0.3.0-build140` running `createDistributable` or `runDistributable` fails on Windows by default and on Linux with certain options enabled (e.g. `linux { shortcut = true }`)

### PR DESCRIPTION
**Pull request by AlexeyTsvetkov**
Fixes #296

### CODE REVIEW

File: gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/tasks/AbstractJPackageTask.kt [hunk 1]
```diff
@@ -187,13 +189,15 @@ abstract class AbstractJPackageTask @Inject constructor(
 
         when (currentOS) {
```
Comment (olonho) [inline gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/tasks/AbstractJPackageTask.kt:190]: Shouldn't `if (targetFormat != TargetFormat.AppImage) {` just go before when?
