### PR TITLE
error message for 32 bit arch

### LINKED ISSUE #560: "Unknown OS arch: x86" when running from command line
build.gradle.kts:
```kt
println("arch is ${System.getProperty("os.arch")}")
dependencies {
    implementation(compose.desktop.currentOs)
}
```

when running gradle from the command line, all commands fail on `implementation(compose.desktop.currentOs)` due to the following error:

```
Unknown OS arch: x86
```
image

works when running from intelliJ, as `System.getProperty("os.arch")` returns `amd64` instead:

image

### PR DESCRIPTION
**Pull request by DetachHead**
closes #560

### CODE REVIEW

File: gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/osUtils.kt [hunk 1]
```diff
@@ -36,6 +36,7 @@ internal val currentArch by lazy {
     when (osArch) {
         "x86_64", "amd64" -> Arch.X64
         "aarch64" -> Arch.Arm64
+        "x86" -> error("32-bit arch not supported: $osArch")
```
Comment (olonho) [inline gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/osUtils.kt:39]: Not sure if x86 any different than anything else here, maybe just change "Unknown" -> "Unsupported" in branch below.

Comment (DetachHead) [reply gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/osUtils.kt]: done

**Review by olonho — APPROVED** [review]
