### PR TITLE
Fix dependencies clash when packaging

### LINKED ISSUE #319: Multi module app packaging issue when having sub modules with the same name
When we have a multi module app with sub modules using same name one of the sub modules are not included in package.

How to reproduce: Create an app with sub modules like this
root
->android
->desktop
->common
--->compose-ui
------>main
------>feature1
------>feature2
--->logic
------>main
------>feature1
------>feature2

### PR DESCRIPTION
**Pull request by AlexeyTsvetkov**
Fixes #319

### CODE REVIEW

File: gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/files/fileUtils.kt [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+import java.io.File
+import java.io.FileInputStream
+import java.security.MessageDigest
+import java.util.*
+import java.util.zip.ZipInputStream
+
+internal fun jarHash(file: File): String {
+    val md5 = MessageDigest.getInstance("MD5")
+    val entryMap = TreeMap<String, ByteArray>()
```
Comment (olonho) [inline gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/files/fileUtils.kt:11]: Why do you need ordered map here?

Comment (olonho) [reply gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/files/fileUtils.kt:11]: Also why not just hash the whole file as binary? Why unpack it?
